### ISSUE TITLE
After update all operations return timeout

### ISSUE THREAD

**Issue by nisbus** [proger/erldocker#8]
This was working before but now when I call `erldocker_api:create`, `docker_container:container(Cid)` and it seems, all other the response is `{error, checkout_timeout}`.  
I see though that the create actually does create the container.  

Some info:

I've tried both with:  
`{docker_http, <<"http://127.0.0.1:2375">>}`    
and  
`{docker_http, <<"http+unix://%2Fvar%2Frun%2Fdocker.sock">>}`
dockerd is started with `-H unix:///var/run/docker.sock -H tcp://0.0.0.0`  and I see in the logs:  
```
INFO[2020-07-16T17:10:29.010369186Z] API listen on [::]:2375                      
INFO[2020-07-16T17:10:29.010399384Z] API listen on /var/run/docker.sock 
```
  
Any ideas on what I could try?  
 

Thanks

**Comment by nisbus** [comment]
Update...somehow a container got started but then I get `docker_container:container(CID)` = `{error, checkout_timeout}` again.  
```
Calling get, <<"http://127.0.0.1:2375/containers/db4b7414743405abfd46878ad9c480660f096050f8272f7c01725cabfd4d45eb/json">>, <<>>
17:21:46.708 UTC [error] Error getting container IP and ports (retrying) checkout_timeout
```
  
curl on the machine with the same url works perfectly.

**Comment by proger** [comment]
Thanks for your report! Could you confirm this works on https://github.com/proger/erldocker/commit/f4187bd8528898162d65d0a4111ae758e9291b84?

**Comment by nisbus** [comment]
Sorry, this seems to be a local issue on my machine.

I found an issue with my fork to begin with.  
It works when I run it locally now.  
  
The issue pops up when I'm running inside a container (docker in docker) but not consistently.

Thanks
